[project]
name = "card-price-trading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ebay-rest>=1.0.14",
    "pip>=25.2",
    "pre-commit>=4.3.0",
    "requests>=2.32.5",
]
